Update yml file

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -35,10 +35,15 @@ jobs:
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
+      # List Tests Directory for Debugging
+      - name: List Tests Directory
+        run: |
+          ls -R tests
+
       # Run Playwright tests and generate output
       - name: Run Playwright Tests with JSON report
         run: |
-          npx playwright test tests/**/*.spec.ts --reporter=json > test-results.json || echo "Tests failed, check results."
+          npx playwright test "tests/**/*.spec.js" --reporter=json > test-results.json || echo "Tests failed, check results."
           cat test-results.json
 
       # Summarize Test Results and Write to Job Summary
